pipeline {
    agent any

    environment {
        VENV_PATH = '/Users/mcdinii/McDinii_backup/Work/Dall_E_3_things/selenium_9-12/selenium_page_9_10/.venv'
        PYTHON_HOME = "${VENV_PATH}/bin/python"
        PATH = "${VENV_PATH}/bin:${env.PATH}"
        PYTHONPATH = "/Users/mcdinii/McDinii_backup/Work/Dall_E_3_things/selenium_9-12/selenium_page_9_10"
    }

    stages {
        stage('Run tests') {
            steps {
                sh '''
                    source ${VENV_PATH}/bin/activate
                    cd /Users/mcdinii/McDinii_backup/Work/Dall_E_3_things/selenium_9-12/selenium_page_9_10/tests
                    ${PYTHON_HOME} -m unittest test_3_add_to_wish_list.FavoritesTest
                '''
            }
        }
    }
}
