pipeline {
    agent any

    stages {
        stage('Set up Python environment') {
            steps {
                script {
                    def pythonHome = tool name: 'Python 3', type: 'Python'
                    env.PYTHON_HOME = "${pythonHome}"
                    env.PATH = "${pythonHome}/bin:${env.PATH}"
                }
                sh '''
                    python3 -m venv selenium/selenium_page_9_10/.venv
                    source selenium/selenium_page_9_10/.venv/bin/activate
                    pip install -r selenium/selenium_page_9_10/req.txt
                '''
            }
        }
        stage('Run tests') {
            steps {
                sh '''
                    source selenium/selenium_page_9_10/.venv/bin/activate
                    cd selenium/selenium_page_9_10/tests
                    python -m unittest test_3_add_to_wish_list.FavoritesTest
                '''
            }
        }
    }
}
